#!/bin/bash
# postinst script for python-pymon2
#
# see: dh_installdeb(1)

set -e

LIB_DIR=/usr/lib/pymon2
VENV_DIR=$LIB_DIR/venv


case "$1" in
    configure)

        cd $VENV_DIR && virtualenv . && cd -

        service pymon2 restart || service pymon2 start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
